# Generated by Django 4.0.2 on 2022-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list4', '0002_alter_list4_id_alter_list4_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list4',
            name='img',
            field=models.CharField(max_length=2550),
        ),
    ]
